### ISSUE TITLE
Starting a search with uppercase letter lets page load infinitely

### ISSUE THREAD

**Issue by Andre601** [Terminal/Discord_Fork#161]
When you go to https://discordbots.co.uk/bots and start the search with an uppercase letter, then the page won't load any profiles and shows the loading animation for an infinite time.
But when you start the search with a lowercase text, it works properly.

Here's a gif for illustration:
![](https://thumbs.gfycat.com/UnderstatedGrotesqueIndianrockpython-size_restricted.gif)

**Comment by lepon01** [comment]
Ah

When there are no results, that appears.
I can replace it with "No results", or just can delete the loading icon.

**Comment by Bowser65** [comment]
It also happens when there should be some results (like `S` for example)

**Comment by Andre601** [comment]
> Ah
>
> When there are no results, that appears.
> I can replace it with "No results", or just can delete the loading icon.

I mean it also happens, when it *should* have results.
In the gif I searched for `Git` and then for `git` but only the second one showed `GitTags` which clearly has `Git` in the name.

**Comment by Andre601** [comment]
Here's the direct link to the gif, since it looks like that GitHub fucks it up.
https://thumbs.gfycat.com/UnderstatedGrotesqueIndianrockpython-size_restricted.gif

**Comment by lepon01** [comment]
I think I fixed it

Just need a `toLowerCase()`
