### ISSUE TITLE
Fix that makes modal work in IE breaks modal when triggered second time

### ISSUE THREAD

**Issue by lepon01** [Terminal/Discord_Fork#26]
Modal doesn't open a second time.

Thanks perryprog

**Comment by perryprog** [comment]
To repro:
- Logout from GitHub, if not already logged out
- On the homepage, click the star button on any bot
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12972285/43498316-63c519e8-9514-11e8-8ed2-1d8689763e31.png">
- Click out of the pane that pops up
- Click on the star button again

**Comment by lepon01** [comment]
This has been fixed in the latest commit 881d2607b64d19e635fc24fdbf90f2687a104c0f.
