### ISSUE TITLE
Buttons are blurry

### ISSUE THREAD

**Issue by Swardu** [Terminal/Discord_Fork#30]
The CSS filter on `.btn.peter-river, input[type="submit"].peter-river` seems to make the buttons blurry. I have removed that on the first button to show the difference.

![image](https://user-images.githubusercontent.com/27481108/43730917-3c52b684-99ad-11e8-9115-657ee6500475.png)

Tested on Firefox 61.0.1

**Comment by Swardu** [comment]
I researched a bit but couldn't find a proper fix. This is what I've found:

- transform: `translateZ(0);` is [supposed to fix it](https://stackoverflow.com/questions/25769671/filter-drop-shadow-is-causing-images-to-blur), but when I test it directly by changing the CSS code, it only lasted 1sec then gets blurry again.

- [box-shadow](https://www.w3schools.com/cssref/css3_pr_box-shadow.asp) is a great alternative without this issue.

**Comment by lepon01** [comment]
I'm not sure why the [actual modesta demo page buttons](https://modesta.alexflipnote.xyz/buttons) don't have this issue, and i can't seem to figure it out as well.

I'll get to work using box-shadow instead then

**Comment by lepon01** [comment]
Actually, is the title blurry as well?

![](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/chrome_2018-08-07_01-05-51.png)

**Comment by lepon01** [comment]
I think I identified the problem, which seems like a problem with ModestaCSS

Half:
![](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/chrome_2018-08-07_01-27-55.png)

Full:
![](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/chrome_2018-08-07_01-28-43.png)

**Comment by lepon01** [comment]
The half makes it blurry

**Comment by lepon01** [comment]
hmmm actually

**Comment by lepon01** [comment]
nvm im wrong

**Comment by lepon01** [comment]
awoo
https://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry

**Comment by lepon01** [comment]
Removing CSS Transform from ModestaCSS fixes the problem.

This has been fixed in the latest commit 53cfc7496e4eec2e55d9fdf25caf51544ff76d42
