### ISSUE TITLE
API endpoint to get individual bot

### ISSUE THREAD

**Issue by MattIPv4** [Terminal/Discord_Fork#63]
It would be nice if there was an endpoint similar to api/bots/all.json but for each individual bot.
Eg. api/bots/:id.json

Thanks.

**Comment by lepon01** [comment]
Other than raising ls.terminal.ink out from the grave, I don't have a good way of getting Jekyll to do this.
I could get Node.js to split the files, but it diverges from the "Use Jekyll only" philosophy...

But at this point, I might as well.

**Comment by MattIPv4** [comment]
Node is an option, as discussed in Discord, it might be possible to populate the api/bots directory with the bot json files during the build process which would allow the whole Jekyll only mantra to stay.

**Comment by lepon01** [comment]
Might also use Discord_Fork as a way to add projects, for a real backend that does everything

**Comment by lepon01** [comment]
I'm currently attempting to attack this using Jekyll itself, by using Ruby plugins

![love4eva](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/Code_2018-09-07_00-58-39.png)

**Comment by lepon01** [comment]
im kinda retarded at jekyll's ruby tho, so please excuse the crud

**Comment by lepon01** [comment]
I've got some output!

```json
{
  "draft": false,
  "categories": [

  ],
  "layout": "item",
  "type": "bots",
  "lang": "en",
  "primary_key": "client_id",
  "client_id": "134133271750639616",
  "application_id": "170237838334492682",
  "pagename": "blargbot",
  "description": "A multipurpose discord bot - Moderation and Fun!",
  "avatar": "https://cdn.discordapp.com/avatars/134133271750639616/1a7e28c9bf7a69475b7928226ca70a40.png",
  "link": "https://invite.blargbot.xyz",
  "prefix": "b!",
  "title": "134133271750639616",
  "slug": "134133271750639616",
  "ext": ".md",
  "tags": [

  ],
  "excerpt": "<iframe src=\"https://blargbot.xyz/\" class=\"ls-iframe\">\n<!--\nThis data was imported from ls.terminal.ink\n-->\n</iframe>\n",
  "permalink": "/bots/134133271750639616/"
}
```

**Comment by lepon01** [comment]
There is a test environment in PR #76.
Preview this [here](https://deploy-preview-76--discordbots.netlify.com/)

[keys.json](https://deploy-preview-76--discordbots.netlify.com/api/bots/keys.json)
[all.json](https://deploy-preview-76--discordbots.netlify.com/api/bots/all.json)
[wendesday's .json file](https://deploy-preview-76--discordbots.netlify.com/api/bots/389083091655852032.json)

**Comment by MattIPv4** [comment]
Looks pretty sweet.
Is there any reason that the invite is called `link` and not `invite`?

**Comment by lepon01** [comment]
It's an agnostic term which applies to both bots and servers

**Comment by MattIPv4** [comment]
Invite would also work for both 🤔

**Comment by lepon01** [comment]
It's also the term that's already in all `.yml` files

**Comment by MattIPv4** [comment]
Ah okay fair enough then. Other than that, looks absolutely great.
