### ISSUE TITLE
[Bug enhancement] White text issue on documentation

### ISSUE THREAD

**Issue by iilukas** [Terminal/Discord_Fork#78]
Good afternoon folks!

https://github.com/Terminal/Discord_Fork/blob/master/_docs/api-reference.md

**Comment by iilukas** [comment]
https://discordimages.com/2qzsE.gif

**Comment by lepon01** [comment]
I've made a fix in PR #80

**Comment by lepon01** [comment]
I've tested it. It's black now.

![kiss later](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/chrome_2018-09-08_01-48-50.png)

**Comment by iilukas** [comment]
Alright.
