### ISSUE TITLE
Codeblocks in markdown ignores empty lines

### ISSUE THREAD

**Issue by Andre601** [Terminal/Discord_Fork#93]
**Describe the bug**
When using codeblocks, the site completely ignores empty lines and acts like those where simple spaces/non existant (see images)

**To Reproduce**
1. Add a bot
2. Use codeblocks (\```) in the long description
3. Have a empty line in the codeblock
4. Save bot and see the result

**Expected behavior**
The site should handle empty lines like GitHub (from where it gets the info) and not remove them, if they don't have 2 spaces, but are in a codeblock.

**Screenshots**
Long description, when adding a bot:
![image](https://user-images.githubusercontent.com/11576465/45586825-3037cc80-b8fd-11e8-8367-d6683cc84633.png)

Actual result (GitHub):
![image](https://user-images.githubusercontent.com/11576465/45586831-48a7e700-b8fd-11e8-8f28-37d5360f77db.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Google Chrome
 - Version 69.0.3497.92 (official build)

**Additional context**
The problem most likely happens when creating a PR.

**Comment by lepon01** [comment]
You readded it wrong.

See [this commit](https://github.com/Terminal/Discord_Fork/commit/96755274502000ada06f9f284cb6f95b0891db0a)

**Comment by lepon01** [comment]
Looks like this is an issue with GitHub itself and not Discord_Fork.

Please contact GitHub support.

[recreated crime scene](https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/2018-09-15_14-45-12.mp4)
